select:
	PGPASSWORD=postgres psql -h  localhost -U  postgres  -d bitmagnet  -c "SELECT * FROM public.torrents ORDER BY created_at DESC LIMIT 10;"
	#SELECT * FROM public.torrents ORDER BY created_at DESC LIMIT 10


